# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-07-17 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernotes',
            old_name='owner',
            new_name='user',
        ),
        migrations.AddField(
            model_name='usernotes',
            name='note',
            field=models.CharField(default=None, max_length=256, verbose_name='note'),
            preserve_default=False,
        ),
    ]
